[Service]
Environment="ACCEPT=ACCEPT"
Environment="ACCEPT_EULA=Y"
Environment="APTINSTALL=rsync"
Environment="APTPURGE=aide"
Environment="ARCH=$(uname -p)"
Environment="ARCHIVE=archive"
Environment="AUTHORIZEDKEYS=authorized_keys"
Environment="BACON=bacon"
Environment="BASHRC=.bashrc"
Environment="BIN=bin"
Environment="BRANCH=main"
Environment="CCACHE_EXEC=/usr/bin/ccache"
Environment="CONF=conf"
Environment="CUBIC=cubic"
Environment="CUBIC=cubic"
Environment="CUSTOMDNSMASQCONF="
Environment="D=d"
Environment="DATE=$(date)"
Environment="DEBIAN_FRONTEND=noninteractive"
Environment="DEFAULT=default"
Environment="DEV=dev"
Environment="DNSMASQ=dnsmasq"
Environment="DNSMASQD=dnsmasq.d"
Environment="DNSMASQSERVICE=dnsmasq.service"
Environment="DOTBASHHISTORY=.bash_history"
Environment="DOTBASHRC=.bashrc"
Environment="DOTBIN=.bin"
Environment="DOTSSH=.ssh"
Environment="ENC=enc"
Environment="ESTABLISHED=ESTABLISHED"
Environment="ETC=etc"
Environment="ETC=etc"
Environment="ETH0=eth0"
Environment="EXIT0=0"
Environment="EXIT1=1"
Environment="EXIT2=2"
Environment="FORWARD=FORWARD"
Environment="GDM3=gdm3"
Environment="GITC=gitc"
Environment="HBIN=.bin"
Environment="HISTCONTROL=ignoreboth"
Environment="HISTFILESIZE=200"
Environment="HISTSIZE=100"
Environment="HOSTNAME=$(hostname)"
Environment="HOSTNAME=$(hostname)"
Environment="HREPO=.repo"
Environment="HSSH=.ssh"
Environment="HTTPS=https"
Environment="IPFORWARD=ip_forward"
Environment="IPV4=ipv4"
Environment="J1NH0=j1nh0"
Environment="LINX=linx"
Environment="LOCALM=local_manifests"
Environment="LOG=log"
Environment="MAIN=main"
Environment="MAPPER=mapper"
Environment="MASQUERADE=MASQUERADE"
Environment="MD=md"
Environment="MESSFAIL=\n\nPROCESS FAIL"
Environment="MESSPASS=\n\nPROCESS PASS"
Environment="MOUNTOPTIONS=rw,relatime,noauto,nodev,noexec,nosuid"
Environment="NAT=nat"
Environment="NET=net"
Environment="NETWORK=network"
Environment="NPROC=$(nproc --ignore=1)"
Environment="OVERRIDE=override"
Environment="PERMDIR=0755"
Environment="PERMFIL=0644"
Environment="PERMROOTDIR=0700"
Environment="PERMROOTFIL=0600"
Environment="POSTROUTING=POSTROUTING"
Environment="PRIMSOL=primsol"
Environment="PROC=proc"
Environment="PWD=$(pwd)"
Environment="RCL=rcl"
Environment="RCLSERVICE=rcl-init.service"
Environment="RCLSERVICEDIR=/etc/systemd/system/rcl-init.service.d"
Environment="RELATED=RELATED"
Environment="REPO=repo"
Environment="ROOT=root"
Environment="ROOT=root"
Environment="SAMBA=samba"
Environment="SERVICE=service"
Environment="SERVICE=service"
Environment="SHADOW=shadow"
Environment="SHADOW=shadow"
Environment="SHARE=share"
Environment="SKEL=skel"
Environment="SSH=ssh"
Environment="SSH=ssh"
Environment="SSHDCONFIG=sshd_config"
Environment="START=start"
Environment="STATE=state"
Environment="STOP=stop"
Environment="SYS=sys"
Environment="SYSCTL=sysctl"
Environment="SYSTEM=system"
Environment="SYSTEMD=systemd"
Environment="TIMESTAMP=time.stamp"
Environment="TMP=tmp"
Environment="UNATTENDED=unattended-upgrades"
Environment="URLARCHIVE=https://archive.ubuntu.com"
Environment="URLGITHUB=https://github.com"
Environment="URLRAW=https://raw.githubusercontent.com"
Environment="USE_CCACHE=1"
Environment="WHOAMI=$(whoami)"
Environment="WLAN0=wlan0"
Environment="ZIP=zip"
