#!/bin/bash -
 if [ "$#" -ne 1 ];then
  echo -e "Dumps contacts from an Android contacts2.db to stdout in vCard format\n"
  echo -e "Usage:  dump-contacts2db.sh path/to/contacts2.db > path/to/output-file.vcf\n"
  echo -e "Dependencies:  perl; base64; sqlite3 / libsqlite3-dev"
  exit 1
 fi
 declare -i cur_contact_id=0
 declare -i prev_contact_id=0
 NEWLINE_QUOTED=`echo -e "'\n'"`
 MS_NEWLINE_QUOTED=`echo -e "'\r\n'"`
 CONTACTS2_PATH=$1
 ORIG_IFS=$IFS
 record_set=`sqlite3 $CONTACTS2_PATH "SELECT raw_contacts._id, raw_contacts.display_name, raw_contacts.display_name_alt, mimetypes.mimetype, REPLACE(REPLACE(data.data1, $MS_NEWLINE_QUOTED, '\n'), $NEWLINE_QUOTED, '\n'), data.data2, REPLACE(REPLACE(data.data4, $MS_NEWLINE_QUOTED, '\n'), $NEWLINE_QUOTED, '\n'), data.data5, data.data6, data.data7, data.data8, data.data9, data.data10, quote(data.data15) FROM raw_contacts, data, mimetypes WHERE raw_contacts.deleted = 0 AND raw_contacts._id = data.raw_contact_id AND data.mimetype_id = mimetypes._id ORDER BY raw_contacts._id, mimetypes._id, data.data2"`
 IFS=`echo -e "\n\r"`
 for row in $record_set;do IFS="|";i=0
  for col in $row;do i=$[i+1]
   case $i in
    1)cur_contact_id=$col;;
    2)cur_display_name=$col;;
    3)cur_display_name_alt=${col/, /\;};;
    4)cur_mimetype=$col;;
    5)cur_data1=$col;;
    6)cur_data2=$col;;
    7)cur_data4=$col;;
    8)cur_data5=$col;;
    9)cur_data6=$col;;
    10)cur_data7=$col;;
    11)cur_data8=$col;;
    12)cur_data9=$col;;
    13)cur_data10=$col;;
    14)cur_data15=$col;;
   esac
  done
  if [ $prev_contact_id -ne $cur_contact_id ]; then
   if [ $prev_contact_id -ne 0 ]; then
    if [ ${#cur_vcard_im_note} -ne 0 ];then cur_vcard_note=$cur_vcard_im_note"\n"$cur_vcard_note;fi
    if [ ${#cur_vcard_note} -ne 0 ];then cur_vcard_note="NOTE:"$cur_vcard_note$'\n';fi
    cur_vcard=$cur_vcard$cur_vcard_nick$cur_vcard_org$cur_vcard_title$cur_vcard_tel$cur_vcard_adr$cur_vcard_email$cur_vcard_url$cur_vcard_note$cur_vcard_photo$cur_vcard_im
    cur_vcard=$cur_vcard"END:VCARD"
    echo $cur_vcard
   fi
   cur_vcard="BEGIN:VCARD"$'\n'"VERSION:3.0"$'\n'
   cur_vcard=$cur_vcard"N:"$cur_display_name_alt$'\n'"FN:"$cur_display_name$'\n'
   cur_vcard_nick=""
   cur_vcard_org=""
   cur_vcard_title=""
   cur_vcard_tel=""
   cur_vcard_adr=""
   cur_vcard_email=""
   cur_vcard_url=""
   cur_vcard_im=""
   cur_vcard_im_note=""
   cur_vcard_note=""
   cur_vcard_photo=""
  fi
  case $cur_mimetype in
   vnd.android.cursor.item/nickname)if [ ${#cur_data1} -ne 0 ];then cur_vcard_nick="NICKNAME:"$cur_data1$'\n';fi;;
   vnd.android.cursor.item/organization)
    if [ ${#cur_data1} -ne 0 ];then cur_vcard_org=$cur_vcard_org"ORG:"$cur_data1$'\n';fi
    if [ ${#cur_data4} -ne 0 ];then cur_vcard_title="TITLE:"$cur_data4$'\n';fi
   ;;
   vnd.android.cursor.item/phone_v2)
    case $cur_data2 in
     1)cur_vcard_tel_type="HOME,VOICE";;
     2)cur_vcard_tel_type="CELL,VOICE,PREF";;
     3)cur_vcard_tel_type="WORK,VOICE";;
     4)cur_vcard_tel_type="WORK,FAX";;
     5)cur_vcard_tel_type="HOME,FAX";;
     6)cur_vcard_tel_type="PAGER";;
     7)cur_vcard_tel_type="OTHER";;
     8)cur_vcard_tel_type="CUSTOM";;
     9)cur_vcard_tel_type="CAR,VOICE";;
    esac
    cur_vcard_tel=$cur_vcard_tel"TEL;TYPE="$cur_vcard_tel_type":"$cur_data1$'\n'
   ;;
   vnd.android.cursor.item/postal-address_v2)
    case $cur_data2 in
     1)cur_vcard_adr_type="HOME";;
     2)cur_vcard_adr_type="WORK";;
    esac
    if [ $cur_data1 != "United States of America" ];then cur_vcard_adr=$cur_vcard_adr"ADR;TYPE="$cur_vcard_adr_type":;;"$cur_data4";"$cur_data7";"$cur_data8";"$cur_data9";"$cur_data10$'\n';cur_vcard_adr=$cur_vcard_adr"LABEL;TYPE="$cur_vcard_adr_type":"$cur_data1$'\n';fi
   ;;
   vnd.android.cursor.item/email_v2)cur_vcard_email=$cur_vcard_email"EMAIL:"$cur_data1$'\n';;
   vnd.android.cursor.item/website)cur_vcard_url=$cur_vcard_url"URL:"$cur_data1$'\n';;
   vnd.android.cursor.item/im)
    case $cur_data5 in
     -1)cur_vcard_im_note=$cur_vcard_im_note"IM-Custom-"$cur_data6": "$cur_data1"\n";;
     0)cur_vcard_im=$cur_vcard_im"X-AIM:"$cur_data1$'\n';cur_vcard_im_note=$cur_vcard_im_note"IM-AIM: "$cur_data1"\n";;
     1)cur_vcard_im=$cur_vcard_im"X-MSN:"$cur_data1$'\n';cur_vcard_im_note=$cur_vcard_im_note"IM-MSN: "$cur_data1"\n";;
     2)cur_vcard_im=$cur_vcard_im"X-YAHOO:"$cur_data1$'\n';cur_vcard_im_note=$cur_vcard_im_note"IM-Yahoo: "$cur_data1"\n";;
     3)cur_vcard_im=$cur_vcard_im"X-SKYPE-USERNAME:"$cur_data1$'\n';cur_vcard_im_note=$cur_vcard_im_note"IM-Skype: "$cur_data1"\n";;
     4)cur_vcard_im=$cur_vcard_im"X-QQ:"$cur_data1$'\n';cur_vcard_im_note=$cur_vcard_im_note"IM-QQ: "$cur_data1"\n";;
     5)cur_vcard_im=$cur_vcard_im"X-GOOGLE-TALK:"$cur_data1$'\n';cur_vcard_im_note=$cur_vcard_im_note"IM-Google-Talk: "$cur_data1"\n";;
     6)cur_vcard_im=$cur_vcard_im"X-ICQ:"$cur_data1$'\n';cur_vcard_im_note=$cur_vcard_im_note"IM-ICQ: "$cur_data1"\n";;
     7)cur_vcard_im=$cur_vcard_im"X-JABBER:"$cur_data1$'\n';cur_vcard_im_note=$cur_vcard_im_note"IM-Jabber: "$cur_data1"\n";;
     *)cur_vcard_im_note=$cur_vcard_im_note"IM: "$cur_data1"\n";;
    esac
   ;;
   vnd.android.cursor.item/photo)
    if [ $cur_data15 != "NULL" ]; then
     photo=`echo $cur_data15 | sed -e "s/^X'//" -e "s/'$//"`
     photo=`echo $photo | perl -ne 's/([0-9a-f]{2})/print chr hex $1/gie' | base64 --wrap=0`
     cur_vcard_photo=$cur_vcard_photo"PHOTO;ENCODING=BASE64;JPEG:"$photo$'\n'
    fi
   ;;
   vnd.android.cursor.item/note)if [ ${#cur_vcard_note} -ne 0 ];then cur_vcard_note=$cur_vcard_note"\n\n"$cur_data1;else cur_vcard_note=$cur_data1;fi;;
  esac
  prev_contact_id=$cur_contact_id
  IFS=`echo -e "\n\r"`
 done
 IFS="|"
 if [ ${#cur_vcard_im_note} -ne 0 ];then cur_vcard_note=$cur_vcard_im_note"\n"$cur_vcard_note;fi
 if [ ${#cur_vcard_note} -ne 0 ];then cur_vcard_note="NOTE:"$cur_vcard_note$'\n';fi
 cur_vcard=$cur_vcard$cur_vcard_nick$cur_vcard_org$cur_vcard_title$cur_vcard_tel$cur_vcard_adr$cur_vcard_email$cur_vcard_url$cur_vcard_note$cur_vcard_photo$cur_vcard_im
 cur_vcard=$cur_vcard"END:VCARD"
 echo $cur_vcard
 IFS=$ORIG_IFS
exit 0
