#aptinstall.sh
~/.bin/aptinstall)
 export USAGE='USAGE: aptinstall ${ b(arebones) | i(nstall) | r(epo) }'
 case "$1" in
  b|barebones)
   for APTBAREBONES in\
    'build-essential'\
    'bash'\
    'bc'\
    'binutils-aarch64-linux-gnu'\
    'binutils-arm-linux-gnueabi'\
    'bison'\
    'bleachbit'\
    'ca-certificates'\
    'cmake'\
    'crunch'\
    'cryptsetup'\
    'cubic'\
    'curl'\
    'deluge'\
    'dosfstools'\
    'ffmpeg'\
    'flatpak'\
    'gcc-12'\
    'gcc-aarch64-linux-gnu'\
    'gcc-arm-linux-gnueabihf'\
    'ghostscript'\
    'git'\
    'git-core'\
    'git-lfs'\
    'gparted'\
    'gzip'\
    'inxi'\
    'libfuse2'\
    'libgoogle-perftools4'\
    'libgoogle-perftools-dev'\
    'libtcmalloc-minimal4'\
    'macchanger'\
    'make'\
    'mtools'\
    'nmap'\
    'pigz'\
    'pip'\
    'qrencode'\
    'remmina'\
    'rename'\
    'screen'\
    'sed'\
    'shc'\
    'solaar'\
    'sqlite'\
    'squashfs-tools'\
    'ssh'\
    'tpm2-tools'\
    'tree'\
    'veracrypt'\
    'vlc'\
    'zip'\
   ;do
    apt install "$APTBAREBONES"
   done
  ;;
  i|install)
   for APTINSTALL in\
    'afnix'\
    'algol68g'\
    'aplus-fsf'\
    'apt-transport-https'\
    'aspectj'\
    'asymptote'\
    'ats2-lang'\
    'bf'\
    'bsdgames'\
    'bsh'\
    'caffeine'\
    'ccache'\
    'clisp'\
    'clojure'\
    'codeblocks'\
    'coffeescript'\
    'dafny'\
    'dc'\
    'dhall'\
    'dislocker'\
    'docker.io'\
    'dosfstools'\
    'ecryptfs-utils'\
    'elixir'\
    'emacs-nox'\
    'erlang'\
    'f2c'\
    'fish'\
    'flex'\
    'fortune-mod'\
    'fp-compiler'\
    'fsharp'\
    'g++'\
    'gambas3-scripter'\
    'gap'\
    'gawk'\
    'gcc'\
    'gcc-aarch64-linux-gnu'\
    'gcc-arm-linux-gnueabi'\
    'gcc-arm-linux-gnueabihf'\
    'gcc-mingw-w64'\
    'gcc-multilib'\
    'gdb'\
    'gdc'\
    'generator-scripting-language'\
    'genius'\
    'gettext'\
    'gforth'\
    'gfortran'\
    'ghc'\
    'gimp'\
    'g++-multilib'\
    'gnat'\
    'gnucobol4'\
    'gnupg'\
    'gnuplot'\
    'gnu-smalltalk'\
    'gobjc'\
    'golang'\
    'golang-go'\
    'gpart'\
    'gparted'\
    'gperf'\
    'gpt'\
    'groovy'\
    'guile-3.0'\
    'haxe'\
    'htop'\
    'icont'\
    'iconx'\
    'idevicerestore'\
    'imagemagick'\
    'intercal'\
    'iverilog'\
    'jasmin-sable'\
    'jq'\
    'kotlin'\
    'ksh'\
    'lame'\
    'lib32ncurses-dev'\
    'lib32readline-dev'\
    'lib32z1-dev'\
    'libgee-0.8-dev'\
    'libgmp-dev'\
    'libimage-exiftool-perl'\
    'libjson-glib-dev'\
    'liblz4-tool'\
    'liblzma-dev'\
    'libmp3lame0'\
    'libmpc-dev'\
    'libmpfr-dev'\
    'libncurses5'\
    'libncurses5-dev'\
    'libncursesw5-dev'\
    'libnlopt-dev'\
    'libpolyml-dev'\
    'libsdl1.2-dev'\
    'libssl-dev'\
    'libvte-2.91-dev'\
    'libxml2'\
    'libxml2-utils'\
    'libxmu-dev'\
    'lisaac'\
    'livescript'\
    'llvm'\
    'lr'\
    'lua5.3'\
    'lynx'\
    'lzip'\
    'lzop'\
    'm4'\
    'maxima'\
    'mdadm'\
    'minizinc'\
    'mono-devel'\
    'mono-mcs'\
    'mono-vbnc'\
    'mtools'\
    'nasm'\
    'neko'\
    'nickle'\
    'nodejs'\
    'node-typescript'\
    'ocaml'\
    'octave'\
    'openjdk-11-jdk'\
    'osmctools'\
    'pari-gp'\
    'parser3-cgi'\
    'pdftk'\
    'perl'\
    'php-cli'\
    'pngcrush'\
    'polyml'\
    'python2'\
    'python2-dev'\
    'python3'\
    'python-dev-is-python3'\
    'python-protobuf'\
    'rakudo'\
    'ratfor'\
    'r-base'\
    'rc'\
    'regina-rexx'\
    'rpi-imager'\
    'ruby'\
    'ruby-mustache'\
    'rustc'\
    'samba'\
    'scala'\
    'schedtool'\
    'scilab-cli'\
    'sendmail'\
    'shc'\
    'simplescreenrecorder'\
    'slsh'\
    'spin'\
    'squirrel3'\
    'surgescript'\
    'swi-prolog'\
    'sysstat'\
    'tcl'\
    'tcsh'\
    'unar'\
    'valac'\
    'veracrypt'\
    'vim'\
    'virt-manager'\
    'vlc'\
    'wabt'\
    'x264'\
    'x265'\
    'xclip'\
    'xsltproc'\
    'xsltproc'\
    'yabasic'\
    'yorick'\
    'zlib1g-dev'\
    'zoem'\
    'zsh'\
   ;do
    apt install "$APTINSTALL"
   done
  ;;
  r|repo)
   for APTREPO in\
    'universe'\
    'multiverse'\
    'restricted'\
    'ppa:cubic-wizard/release'\
    'ppa:unit193/encryption'\
    'deb http://archive.ubuntu.com/ubuntu/ jammy universe main multiverse restricted'\
    'deb http://security.ubuntu.com/ubuntu/ jammy-security universe main multiverse restricted'\
    'deb http://archive.ubuntu.com/ubuntu/ jammy-updates universe main multiverse restricted'\
    'deb http://archive.ubuntu.com/ubuntu/ focal universe main multiverse restricted'\
    'deb http://security.ubuntu.com/ubuntu/ focal-security universe main multiverse restricted'\
    'deb http://archive.ubuntu.com/ubuntu/ focal-updates universe main multiverse restricted'\
   ;do
    sudo add-apt-repository -y "$APTREPO"
   done
  ;;
  *)usage;;
 esac
;;
