#!/bin/bash -
 export USAGE='USAGE: aptextra ${ all | libdvd-pkg | mega | visualstudio }'
 case "$1" in
  libdvd-pkg)
   aptu
   for APTLIBDVDPKG in\
    'libdvdcss-dev'\
    'libdvdcss2'\
    'libdvdread-dev'\
    'libdvdread8'\
    'libdvdnav4'\
    'libdvd-pkg'\
   ;do
    apt-get install "$APTLIBDVDPKG"
   done
   dpkgreconf libdvd-pkg
  ;;
  mega)
   wget https://mega.nz/linux/repo/xUbuntu_24.04/amd64/megacmd-xUbuntu_24.04_amd64.deb&&apt-get install "$PWD/megacmd-xUbuntu_24.04_amd64.deb"
  ;;
  visualstudio)
   apt-get install -y wget gpg apt-transport-https
   wget -qO- https://packages.microsoft.com/keys/microsoft.asc|gpg --dearmor>packages.microsoft.gpg
   install -D -o root -g root -m 644 packages.microsoft.gpg /etc/apt/keyrings/packages.microsoft.gpg
   echo "deb [arch=amd64,arm64,armhf signed-by=/etc/apt/keyrings/packages.microsoft.gpg] https://packages.microsoft.com/repos/code stable main"|tee /etc/apt/sources.list.d/vscode.list>/dev/null
   rm -f packages.microsoft.gpg
   apt-get update
   apt-get install -y code
  ;;
  all)
   for APTEXTRA in\
    'libdvd-pkg'\
    'mega'\
    'visualstudio'\
   ;do aptextra "$APTEXTRA";done
  ;;
  *)usage;;
 esac
exit 0
