#!/bin/bash -
 for MP4 in *mp4;do
  ffmpeg -n -i "$MP4" -vn -acodec libmp3lame -ac 2 -ab 320k -ar 48000 "${MP4%.*}.mp3"
  if [ "$1" == '-k' ];then echo "$MP4 to ${MP4%.*}.mp3 completed";else rm "$MP4";fi
 done
exit 0
