#STANDARD CANTRIPS
alias ls='ls --color=auto'
alias dir='dir --color=auto'
alias vdir='vdir --color=auto'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
alias diff='diff --color=auto'
alias ip='ip --color=auto -a'
alias df='df -h'
alias du='du -sh'
alias cp='cp -Rfv'
alias mv='mv -v'
alias nn='nano -ic'
alias rr='rm -rf'
alias cub='cubic -v &> /dev/null &'
alias dfs="df|grep 'Filesystem'&&df|grep -v 'Filesystem'|sort"
alias dfw='while true;do df -h;date;sleep 1;clear;done'
alias fdl='fdisk -l'
alias ipa='ip addr'
alias mkt='mkdir -vp ./tmp/&&cd ./tmp/'
alias scp='scp -r'
alias ssh='ssh -X'
alias top='top -1'
alias free='free -h'
alias grep='grep --color'
alias hold='echo HOLDING&&read NULLVAR'
alias less='less -N'
alias nano='nano -ic'
alias ping='ping -c 4'
alias crontabe='crontab -e'
#LISTING
alias cl='clear;ls --color'
alias l1='ls -1 --color'
alias la='ls -a --color'
alias lb='lsblk'
alias lc='lscpu'
alias ld='ls -d */'
alias li='ls -i --color'
alias ll='ls -l1Ah --color'
alias lt='ls -1t --color'
alias lU='ls -1U --color'
alias lx='ls -x --color'
alias lsd='ls -1 --color /dev/sd*'
alias cl1='clear;sync;ls -h1 --color'
alias cla='clear;sync;ls -ha --color'
alias cll='clear;sync;ls -lh --color'
alias cls='clear;sync;ls -h --color'
alias clw='ls|wc -l'
alias clla='clear;sync;ls -lha --color'
#APT
alias apt='ACCEPT_EULA=Y DEBIAN_FRONTEND=noninteractive apt -y --install-recommends'
alias apti='apt install "$@"'
alias aptc='apt -y clean'
alias aptac='apt -y autoclean'
alias aptar='apt -y autoremove'
alias aptf='apt install -f -y'
alias aptp='apt purge "$@"'
#TRAVERSAL
alias ..='cd ../'
alias ...='cd ../../'
alias ....='cd ../../../'
alias .....='cd ../../../../'
alias ......='cd ../../../../../'
alias .......='cd ../../../../../../'
alias ........='cd ../../../../../../../'
alias .........='cd ../../../../../../../../'
alias ..........='cd ../../../../../../../../../'
alias ...........='cd ../../../../../../../../../../'
alias ............='cd ../../../../../../../../../../../'
alias .............='cd ../../../../../../../../../../../../'
