#!/bin/bash -
 if [ ! -f ~/.ssh/j1nh0.github ];then echo 'Github token not found!'&&exit 1;else
  TOKEN=$(cat ~/.ssh/j1nh0.github)
  export USAGE='USAGE: gitremote ${ l(ist) || c(reate) [private || public] || d(elete) }'
  case "$1" in
   l|list)
    curl -L\
     -H "Accept: application/vnd.github+json"\
     -H "Authorization: Bearer $TOKEN"\
     -H "X-GitHub-Api-Version: 2022-11-28"\
     https://api.github.com/users/j1nh0/repos?per_page=100|\
     grep -w 'html_url'|\
     grep -wv '"html_url": "https://github.com/j1nh0",'|\
     cut -d' ' -f6|\
     cut -c2-|\
     sed -e 's/",$//g'
   ;;
   c|create)
    export USAGE='USAGE: gitremote c ${ public | private }'
    case "$2" in
     public)
      curl -L -X POST\
       -H "Accept: application/vnd.github+json"\
       -H "Authorization: Bearer $TOKEN"\
       -H "X-GitHub-Api-Version: 2022-11-28"\
       https://api.github.com/user/repos -d "{\"name\":\"$(basename $PWD)\"}";;
     private)
      curl -L -X POST\
       -H "Accept: application/vnd.github+json"\
       -H "Authorization: Bearer $TOKEN"\
       -H "X-GitHub-Api-Version: 2022-11-28"\
       https://api.github.com/user/repos -d "{\"name\":\"$(basename $PWD)\"}";;
     *)usage;;
    esac
   ;;
   d|delete)
    curl -L -X DELETE\
     -H "Accept: application/vnd.github+json"\
     -H "Authorization: Bearer $TOKEN"\
     -H "X-GitHub-Api-Version: 2022-11-28"\
     https://api.github.com/repos/j1nh0/"$2";;
   *)usage;;
  esac
 fi
exit 0
