/*THIS NEEDS WORK*/
/*bootconfig.c*/
}else if(strcmp(applet,"bootconfig")==0){
 char *grubcfg[10000]={
  "if loadfont /boot/grub/font.pf2 ; then",
  " set gfxmode=auto",
  " insmod efi_gop",
  " insmod efi_uga",
  " insmod gfxterm",
  " terminal_output gfxterm",
  "fi",
  "set menu_color_normal=green/black",
  "set menu_color_highlight=black/green",
  "set timeout=5",
  "menuentry \"ramGUI\" {",
  " set gfxpayload=keep",
  " linux /casper/vmlinuz boot=casper file=/cdrom/preseed/$SEED.seed maybe-ubiquity toram quiet splash noprompt ---",
  " initrd /casper/initrd.lz",
  "}",
  "menuentry \"vanillaGUI\" {",
  " set gfxpayload=keep",
  " linux /casper/vmlinuz  boot=casper file=/cdrom/preseed/$SEED.seed maybe-ubiquity quiet splash noprompt ---",
  " initrd /casper/initrd.lz",
  "}",
  "menuentry \"ramGUISafeGraphics\" {",
  " set gfxpayload=keep",
  " linux /casper/vmlinuz nomodeset boot=casper file=/cdrom/preseed/$SEED.seed maybe-ubiquity toram quiet splash noprompt ---",
  " initrd /casper/initrd.lz",
  "}",
  "menuentry \"vanillaGUISafeGraphics\" {",
  " set gfxpayload=keep",
  " linux /casper/vmlinuz nomodeset boot=casper file=/cdrom/preseed/$SEED.seed maybe-ubiquity maybe-ubiquity quiet splash noprompt ---",
  " initrd /casper/initrd.lz",
  "}",
  "menuentry \"ramCLI\" {",
  " set gfxpayload=keep",
  " linux /casper/vmlinuz boot=casper file=/cdrom/preseed/$SEED.seed maybe-ubiquity toram quiet splash noprompt --- 3",
  " initrd /casper/initrd.lz",
  "}",
  "menuentry \"vanillaCLI\" {",
  " set gfxpayload=keep",
  " linux /casper/vmlinuz boot=casper file=/cdrom/preseed/$SEED.seed maybe-ubiquity quiet splash noprompt --- 3",
  " initrd /casper/initrd.lz",
  "}",
  "menuentry \"ramCLISafeGraphics\" {",
  " set gfxpayload=keep",
  " linux /casper/vmlinuz nomodeset boot=casper file=/cdrom/preseed/$SEED.seed maybe-ubiquity toram quiet splash noprompt --- 3",
  " initrd /casper/initrd.lz",
  "}",
  "menuentry \"ramCLISafeGraphics\" {",
  " set gfxpayload=keep",
  " linux /casper/vmlinuz nomodeset boot=casper file=/cdrom/preseed/$SEED.seed maybe-ubiquity quiet splash noprompt --- 3",
  " initrd /casper/initrd.lz",
  "}",
  "menuentry \"memtest86plus\" {",
  " linux16 /install/mt86plus",
  "}"
 };
 char *loopbackcfg[10000]={
  "menuentry \"ramGUI\" {",
  " set gfxpayload=keep",
  " linux /casper/vmlinuz boot=casper file=/cdrom/preseed/$SEED.seed maybe-ubiquity iso-scan/filename=${iso_path} toram quiet splash noprompt ---",
  " initrd /casper/initrd.lz",
  "}",
  "menuentry \"vanillaGUI\" {",
  " set gfxpayload=keep",
  " linux /casper/vmlinuz boot=casper file=/cdrom/preseed/$SEED.seed maybe-ubiquity iso-scan/filename=${iso_path} quiet splash noprompt ---",
  " initrd /casper/initrd.lz",
  "}",
  "menuentry \"ramGUISafeGraphics\" {",
  " set gfxpayload=keep",
  " linux /casper/vmlinuz nomodeset boot=casper file=/cdrom/preseed/$SEED.seed maybe-ubiquity iso-scan/filename=${iso_path} toram quiet splash noprompt ---",
  " initrd /casper/initrd.lz",
  "}",
  "menuentry \"vanillaGUISafeGraphics\" {",
  " set gfxpayload=keep",
  " linux /casper/vmlinuz nomodeset boot=casper file=/cdrom/preseed/$SEED.seed maybe-ubiquity iso-scan/filename=${iso_path} quiet splash noprompt ---",
  " initrd /casper/initrd.lz",
  "}",
  "menuentry \"ramCLI\" {",
  " set gfxpayload=keep",
  " linux /casper/vmlinuz boot=casper file=/cdrom/preseed/$SEED.seed maybe-ubiquity iso-scan/filename=${iso_path} toram quiet splash noprompt --- 3",
  " initrd	/casper/initrd.lz",
  "}",
  "menuentry \"vanillaCLI\" {",
  " set gfxpayloa=keep",
  " linux /casper/vmlinuz boot=casper file=/cdrom/preseed/$SEED.seed maybe-ubiquity iso-scan/filename=${iso_path} quiet splash noprompt --- 3",
  " initrd /casper/initrd.lz",
  "}",
  "menuentry \"ramCLISafeGraphics\" {",
  " set gfxpayload=keep",
  " linux /casper/vmlinuz nomodeset boot=casper file=/cdrom/preseed/$SEED.seed maybe-ubiquity iso-scan/filename=${iso_path} toram quiet splash noprompt --- 3",
  " initrd	/casper/initrd.lz",
  "}",
  "menuentry \"vanillaCLISafeGraphics\" {",
  " set gfxpayloa=keep",
  " linux /casper/vmlinuz nomodeset boot=casper file=/cdrom/preseed/$SEED.seed maybe-ubiquity iso-scan/filename=${iso_path} quiet splash noprompt --- 3",
  " initrd /casper/initrd.lz",
  "}",
  "menuentry \"memtest86plus\" {",
  " linux16 /install/mt86plus",
  "}"
 };
 system("> grub.cfg");
 system("> loopback.cfg");
 while(grubcfg[i]!=NULL){
  sprintf(cmd,"echo \"%s\">>grub.cfg",grubcfg[i]);
  system(cmd);
  i++;
 };
 while(loopbackcfg[j]!=NULL){
  sprintf(cmd,"echo \"%s\">>loopback.cfg",loopbackcfg[j]);
  system(cmd);
  j++;
 };
