#!/bin/bash -
#VARIABLE DECLARE
if [ -f $HOME/.linx/etc/environment ];then source $HOME/.linx/etc/environment;else echo 'Environment not found!';exit 1;fi
if [ -f $HOME/.linx/etc/array ];then source $HOME/.linx/etc/array;else echo 'Array not found!';exit 1;fi
export USAGE='USAGE: drop ${ e(verything) | h(dd) | m(em) }'
#FUNCTION DECLARE
drop(){
 case "$ARG1" in
  e|everything)for INT in $(seq 1 3);do echo "$INT"|sudo tee /proc/sys/vm/drop_caches;sync;done;;
  h|hdd)echo '2'|sudo tee /proc/sys/vm/drop_caches;sync;;
  m|mem)echo '1'|sudo tee /proc/sys/vm/drop_caches;sync;;
  *)usage;;
 esac
};
#MAIN LOGIC
drop;sync;
#MAIN EXIT
exit 0
