#!/bin/bash -
 export USAGE='USAGE: drop ${ e(verything) | h(dd) | m(em) }'
 case "$1" in
  e|everything)for INT in $(seq 1 3);do echo "$INT"|sudo tee /proc/sys/vm/drop_caches;sync;done;;
  h|hdd)echo '2'|sudo tee /proc/sys/vm/drop_caches;sync;;
  m|mem)echo '1'|sudo tee /proc/sys/vm/drop_caches;sync;;
  *)usage;;
 esac
exit 0
